// <auto-generated />
namespace _60331_Glotov.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Nick : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Nick));
        
        string IMigrationMetadata.Id
        {
            get { return "201806092119416_Nick"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
